snowcap_admin_demo:
    resource: "@SnowcapAdminDemoBundle/Controller"

snowcap_datalist_demo:
    resource: "@SnowcapDatalistDemoBundle/Controller/"
    prefix: datalist

snowcap_i18n_demo:
    resource: "@SnowcapI18nDemoBundle/Controller/"
    type: annotation_i18n
    prefix: i18n

#snowcap_i18n_demo:
#    resource: "@SnowcapI18nDemoBundle/Resources/config/routing.yml"
#    type: yaml_i18n
#    prefix: i18n

snowcap_admin:
    resource: "@SnowcapAdminBundle/Resources/config/routing.yml"
    prefix: admin

snowcap_im:
    resource: "@SnowcapImBundle/Resources/config/routing.yml"

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal